# Users can import user customized yaml files or library provided default yaml files
includes: []
  # - $/configs/defaults.yaml
  # In the above example path, '$/' indicates the library directory which contains the config folder

preprocessing_args:
  top_word_vocab: 70000
  word_emb_size: 300
  share_vocab: True
  min_word_freq: 1
  dataset: "kinship"
  preprocess: False
  resume: False

model_args:
  model: "distmult" # conve, complex, distmult, gcn_distmult, gcn_complex, ggnn_distmult
  graph_initialization_name: "defaults"
  # for kgc models
  embedding_dim: 200
  embedding_shape1: 20 # for conve
  conve_hidden_size: 9728 # for conve
  use_bias: False # for conve
  hidden_drop: 0.25
  input_drop: 0.2
  feat_drop: 0.2

  graph_construction_args:
    graph_construction_private:
      dynamic_init_graph_name: null
      merge_strategy: null
      edge_strategy: null

    graph_construction_share:
      timeout: null
      port: null

  graph_embedding_args:
    graph_embedding_share:
      num_layers: 2
      direction_option: "bi_sep"

training_args:
  batch_size: 128 # batch size
  epochs: 200 # number of maximal training epochs
  lr: 0.0005 # learning rate
  loader_threads: 4
  l2: 0.0
  label_smoothing: 0.1


checkpoint_args:
  out_dir: "out/kgc/kinship"


env_args:
  seed: 1234
  gpu: 1
  no_cuda: false
